apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-go-http-server
  name: simple-go-http-server
spec:
  ports:
  - name: http
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: simple-go-http-server
  type: ClusterIP
